spring.application.name=TrabalhoDenis

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=PostgreSQL

# Faz o Spring criar/atualizar as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update
# update: ao iniciar, o Hibernate lê todas as classes anotadas com @Entity, compara o schema atual do banco com o que as anotações descrevem, e aplica as diferenças.
# Se a tabela não existe, ele cria. Se existe mas falta uma coluna, ele adiciona. O que ele nunca faz no modo update é apagar colunas ou tabelas existentes

# Mostra o SQL gerado no console
spring.jpa.show-sql=true

#precisa de um jwt config
app.jwt.secret=segredo-super-seguro-123456789101112
app.jwt.expiration=86400000

# configura o rabbitmq
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=secret